### ISSUE TITLE
GLPI 10 compatible?

### ISSUE THREAD

**Issue by lupin3rd** [mrsric/glpiticket-lhc#1]
Hi,
2 question:

1) Can you add a setting option to disable SSL verify? I think that is usefull...
I disable with some modification in glpiticket/bootstrap/bootstrap.php, i added:
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

2) When i try to create a ticket i have the error:
Unable to create session_token: ["ERROR_APP_TOKEN_PARAMETERS_MISSING","parametro app_token mancante; visualizza documentazione nel tuo browser a http://xxxxxxxxxxx/apirest.php/#ERROR_APP_TOKEN_PARAMETERS_MISSING"]400

I'm using last stable release of GLPI, 10.0.1.

Thank you!

**Comment by mrsric** [comment]
Hi @lupin3rd,

Thanks for the contribution!

1. Add Option to disable SSL verify

2. The error **ERROR_APP_TOKEN_PARAMETERS_MISSING** is related to not finding the apptoken parameter. Added in Header both "app_token" and "app-token".

Please validate.

https://github.com/mrsric/glpiticket-lhc/commit/5e0afd89203a6544a183a4bf2bb730f738f1a4d9

**Comment by lupin3rd** [comment]
Hi @mrsric ,
i confirm that now lhc create correctly tickets on GLPI 10.0.1 and get URLs.

I'm testing all functionality...

A first bug: GLPI integration settings don't show correctly the status of "Disable SSL verify" form field.

Thank you very much for this plugin!

**Comment by mrsric** [comment]
Hi @lupin3rd,

Thanks for the tests.

Adjusted the bug: _GLPI integration settings don't show correctly the status of "Disable SSL verify" form field._

Please validate.

https://github.com/mrsric/glpiticket-lhc/commit/5fa4f797e151fb2cd6765117706417464bdb1949

**Comment by lupin3rd** [comment]
Bug solved.
